//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRegionalismos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCatalogoPalabras
    {
        public string DescripcionPalabra { get; set; }
        public string DescripcionPais { get; set; }
        public string DescripcionIdioma { get; set; }
        public string Definicion { get; set; }
        public int IdPalabra { get; set; }
        public int IdIdioma { get; set; }
        public string IdPais { get; set; }
        public int IdDefinicion { get; set; }
    }
}
